@baseUrl = http://localhost:4004




##to post author 
POST {{baseUrl}}/admin/books
Content-Type: application/json

{

"tile" : " "  ,
"genre" : 3  
}


#------------------------------
###to create new author 

POST {{baseUrl}}/admin/Authors
Content-Type: application/json

{
    
    "name" : "Friedrich Schiller",
    "dateodBirth" : "1564-04-26",
    "dateofDeath" : "1554-04-26"
   


}


###to fetch the data 
GET {{baseUrl}}/admin/Authors
Accept-Language: de


#### create new 

POST {{baseUrl}}/admin/Authors
Content-Type: application/json

{
    
    "name" : "THird version"
}


#### read etag 

GET {{baseUrl}}/admin/Authors({{ID}})

@Etag1 = {{createNewAuthor.respo}}



####################
post 
